### PR TITLE
Links in bottom bar added

### LINKED ISSUE #6: Add links to bottom bar
Add the following links to the footer of the page

- Telegram Join Link
- Gitter Join Link
- Github Link for Organisation

### PR DESCRIPTION
**Pull request by nityanandagohain**
fixes #6 
https://nityanandagohain.github.io/yogdaan.github.io/

### CODE REVIEW

**Comment by gabru-md** [comment]
These look cool, but I cannot see them at the bottom of the page. Can you please see to it?
Footer needs to stick to the bottom of the page.

Rest it is cool! Please do the change so that we can merge?

**Comment by nityanandagohain** [comment]
sure

**Comment by nityanandagohain** [comment]
done @gabru-md

**Comment by gabru-md** [comment]
@xeon-zolt are you sure we needed the `Github` link to contain the link to orgmanager
and not to `https://github.com/yogdaan`

**Comment by xeon-zolt** [comment]
should we have 4 links joins us, github, telegram and gitter

**Comment by gabru-md** [comment]
yes I suppose

**Comment by nityanandagohain** [comment]
Ok should i send a pr for that

**Comment by xeon-zolt** [comment]
Why not !!

**Pull request merged**
