### PR TITLE
added minimal landing page with no links

### PR DESCRIPTION
**Pull request by xeon-zolt**
https://xeon-zolt.github.io/yogdaan.github.io/

### CODE REVIEW

**Comment by gabru-md** [comment]
Please change page title

**Comment by xeon-zolt** [comment]
kafi changes karne h

**Comment by xeon-zolt** [comment]
should we keep it dark or light ??
then we can start by adding a navigation bar

**Comment by nityanandagohain** [comment]
nice :sparkles:

**Comment by nityanandagohain** [comment]
dark is looking good.

**Pull request merged**
