### PR TITLE
Improved Bottom Bar Responsiveness

### PR DESCRIPTION
**Pull request by khanna98**

### CODE REVIEW

**Comment by khanna98** [comment]
But this works fine on my browser ?!
screenshot_20180626_205628

**Comment by xeon-zolt** [comment]
@gabru-md can you test ??
maybe some problem on my side

**Comment by xeon-zolt** [comment]
@khanna98 can you attach screenshots in other screen sizes

**Comment by gabru-md** [comment]
@khanna98 can you please provide us with a sample deployment on surge?
so that we can review and check if the problem persists :smile:

**Comment by khanna98** [comment]
screenshot_20180627_180306
This is the mobile view.

**Pull request merged**
