### PR TITLE
Started best-practices.md

### PR DESCRIPTION
**Pull request by xeon-zolt**
things learned from experiences and mistakes makes you better

### CODE REVIEW

**Comment by xeon-zolt** [comment]
or we can keep improving it one by one ?

**Comment by gabru-md** [comment]
But we do need an issue for the same I guess.
Where people can comment about what they consider to be among best practice

**Comment by xeon-zolt** [comment]
@gabru-md sure create one please and link this with that issue

**Comment by gabru-md** [comment]
Link to Issue : [#13](https://github.com/yogdaan/yogdaan.github.io/issues/13)

**Pull request merged**
